name: eds_app
description: Eds test project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  drift: ^1.7.1
  sqlite3_flutter_libs: ^0.5.8
  path_provider: ^2.0.11
  path: ^1.8.1
  dio: ^4.0.6
  cached_network_image: ^3.2.1
  intl: ^0.17.0
  flutter_bloc: ^8.0.1
  bloc_concurrency: ^0.2.0
  freezed_annotation: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  drift_dev: ^1.7.0
  build_runner: ^2.2.0
  freezed: ^2.0.5
  analyzer: ^4.2.0

flutter:
  uses-material-design: true
